### ISSUE TITLE
Running problems with the UAV model:six rotors or quadrotors?

### ISSUE THREAD

**Issue by DRAEYE** [truecarfield/tud_firefly_landing_sim#1]
Sorry, I failed to noticed that you are using a six rotor model , so the simulation corrupted when I run it.I wonder whether the simulation is suitable for a quadrotor?

**Comment by truecarfield** [comment]
Hi, sorry for the later reply. Sure, you can of course simulate with your own delevloped UAV model. Currently in the simulator only the Hexrotor is implemented.
